version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: sponomareva/foodgram:latest
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - ./.env

  frontend:
    image: sponomareva/foodgram-frontend:latest
    volumes:
      - result_build:/app/result_build/build/

  nginx:
    image: nginx:1.19.3-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - result_build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/static/
    depends_on:
      - backend

volumes:
  result_build:
  postgres_data:
  static_value:
  media_value:
