# Generated by Django 2.2.16 on 2022-08-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
